package wotoErrors

const (
	MessageInvalidUsernameFormat    = "Invalid username entered."
	MessageInvalidPasswordFormat    = "Invalid password entered."
	MessageUsernameExists           = "The username already exists."
	MessageWrongUsername            = "The username is wrong."
	MessageWrongPassword            = "The password is wrong."
	MessageInvalidAuthKeyFormat     = "Invalid auth key entered."
	MessageInvalidAccessHashFormat  = "Invalid access hash entered."
	MessageWrongAuthKey             = "The auth key is wrong."
	MessageLoginAccessHashExpired   = "The access hash is expired."
	MessageInvalidFirstName         = "Invalid first name entered."
	MessageInvalidLastName          = "Invalid last name entered."
	MessageInvalidTitle             = "Invalid title entered."
	MessageAlreadyAuthorized        = "You are already authorized; try using LogOut method."
	MessageNotAuthorized            = "You are not authorized; try using LoginUser method."
	MessageNotModified              = "The value is not modified."
	MessageBioTooLong               = "The bio is too long."
	MessageUserNotFound             = "Target user not found."
	MessageFirstNameTooLong         = "The first name is too long."
	MessageLastNameTooLong          = "The last name is too long."
	MessageInvalidUsernameAndUserId = "Invalid username and user id entered."
	MessageMethodNotImplemented     = "The method is not implemented yet."
	MessagePermissionDenied         = "Permission denied."
	MessageKeyNotFound              = "Key not found."
	MessageInvalidTelegramId        = "Invalid telegram id entered."
	MessageInvalidEmail             = "Invalid email entered."
)
